# Generated by Django 2.2.28 on 2023-02-07 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(default='000', max_length=50)),
                ('capacity', models.IntegerField(default=4)),
                ('vehicle_type', models.CharField(default='SEDAN', max_length=100)),
                ('special_info', models.CharField(default='', max_length=200)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('arrive_date', models.DateTimeField(help_text='Format: 2023-02-01 12:00')),
                ('passenger_num', models.PositiveIntegerField(default=1)),
                ('sharable', models.BooleanField()),
                ('vehicle_type', models.CharField(blank=True, default='None', max_length=100)),
                ('status', models.CharField(default='open', max_length=20)),
                ('special_request', models.CharField(blank=True, default='', max_length=400)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ride.DriverVehicle')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('sharer', models.ManyToManyField(blank=True, related_name='sharer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
