# Generated by Django 4.1.5 on 2023-01-30 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=100)),
                ('arrive_date', models.DateTimeField(help_text='Format: 2020-01-01 12:00')),
                ('passenger_num', models.PositiveIntegerField(default=1)),
                ('whether_share', models.BooleanField()),
                ('max_share_num', models.PositiveIntegerField(default=0, help_text='If you do not want to share please choose 0')),
                ('required_special', models.CharField(blank=True, max_length=400)),
                ('status', models.CharField(default='open', max_length=20)),
                ('share_name', models.CharField(blank=True, default='', max_length=50)),
                ('share_num', models.PositiveIntegerField(default=0)),
                ('driver_name', models.CharField(blank=True, default='', max_length=50)),
                ('driver_license', models.CharField(blank=True, default='', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
