# Generated by Django 4.1.5 on 2023-02-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_driver_rename_whether_share_rideorder_sharable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='type',
        ),
    ]
