# Generated by Django 4.1.5 on 2023-02-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0008_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='Vtype',
            field=models.CharField(default='SEDAN', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='brand',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='special_info',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
