# Generated by Django 4.1.5 on 2023-02-03 01:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0009_driver_vtype_driver_brand_driver_special_info_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Driver',
            new_name='DriverVehicle',
        ),
        migrations.RenameField(
            model_name='rideorder',
            old_name='addr',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='rideorder',
            old_name='driver_license',
            new_name='driver_plate',
        ),
        migrations.RenameField(
            model_name='rideorder',
            old_name='share_name',
            new_name='sharer_name',
        ),
        migrations.RenameField(
            model_name='rideorder',
            old_name='share_num',
            new_name='sharer_num',
        ),
    ]
