# Generated by Django 4.1.5 on 2023-02-03 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0010_rename_driver_drivervehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideorder',
            name='sharer_name',
        ),
        migrations.AddField(
            model_name='rideorder',
            name='sharer',
            field=models.ManyToManyField(blank=True, related_name='sharer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
