# Generated by Django 4.1.5 on 2023-02-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0011_remove_rideorder_sharer_name_rideorder_sharer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivervehicle',
            old_name='Vtype',
            new_name='vehicle_type',
        ),
        migrations.AddField(
            model_name='rideorder',
            name='vehicle_type',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
    ]
