# Generated by Django 4.1.5 on 2023-02-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0013_rename_required_special_rideorder_special_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideorder',
            name='driver_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='special_request',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
