# Generated by Django 4.1.5 on 2023-02-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0014_alter_rideorder_driver_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideorder',
            name='driver_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
