# Generated by Django 4.1.5 on 2023-02-04 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0015_alter_rideorder_driver_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideorder',
            name='driver_id',
        ),
        migrations.AddField(
            model_name='rideorder',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ride.drivervehicle'),
        ),
    ]
